"use strict";const KEY="codebhavya.fullstack.progress.v1",levels=window.FULLSTACK_LEVELS,lessons=window.FULLSTACK_LESSONS||{};const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);const n=Math.max(1,Math.min(30,Number(new URLSearchParams(location.search).get("level"))||1)),lesson=lessons[n];let traceIndex=0;
function nav(){document.getElementById("levelNav").innerHTML=levels.map(l=>`<a class="${l.n===n?"active":""} ${l.available?"":"locked"}" href="${l.available?`lesson.html?level=${l.n}`:"#"}"><b>${String(l.n).padStart(2,"0")}</b> ${esc(l.title)}${l.available?"":" · planned"}</a>`).join("")}
function codeBox(c,label="Example"){return `<div class="code-box"><header><span>${esc(label)}</span><button data-copy="${esc(c)}">Copy</button></header><pre><code>${esc(c)}</code></pre></div>`}
function render(){if(!lesson){document.getElementById("lessonMain").innerHTML=`<section class="lesson-section"><p class="section-label">PLANNED LEVEL</p><h2>${esc(levels[n-1].title)}</h2><p>This level is part of the complete roadmap and will be added after the Web Foundations stage is validated.</p><a class="button primary" href="lesson.html?level=1">Open available lessons</a></section>`;return}
document.title=`Level ${n}: ${lesson.title} | CodeBhavya`;
document.getElementById("lessonMain").innerHTML=`<section class="lesson-hero"><p class="eyebrow">LEVEL ${String(n).padStart(2,"0")} · ${esc(lesson.kicker)}</p><h1>${esc(lesson.title)}</h1><p>${esc(lesson.summary)}</p><div class="lesson-meta"><span>${esc(lesson.duration)}</span><span>${lesson.concepts.length} core concepts</span><span>${lesson.quiz.length} knowledge checks</span></div></section>
<section class="lesson-section"><p class="section-label">LEARNING OUTCOMES</p><h2>What you will be able to explain and build</h2><div class="objectives">${lesson.outcomes.map((x,i)=>`<div><b>0${i+1}</b><span>${esc(x)}</span></div>`).join("")}</div></section>
${lesson.concepts.map((c,i)=>`<section class="lesson-section"><p class="section-label">CONCEPT ${i+1}</p><h2>${esc(c.title)}</h2><p>${esc(c.text)}</p>${c.points?`<ul>${c.points.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`:""}${c.code?codeBox(c.code,c.label||"WORKED EXAMPLE")+(c.output?`<h3>Expected result</h3><div class="code-box"><pre>${esc(c.output)}</pre></div>`:""):""}</section>`).join("")}
<section class="lesson-section"><p class="section-label">INTERACTIVE LEARNING · VISUAL FLOW</p><h2>${esc(lesson.flowTitle)}</h2><div class="visual-flow">${lesson.flow.map((x,i)=>`<div><b>${i+1}. ${esc(x.name)}</b><span>${esc(x.detail)}</span></div>`).join("")}</div></section>
<section class="lesson-section"><p class="section-label">PROGRAM TRACING</p><h2>Follow the system one step at a time</h2><div class="trace"><div><div class="trace-code" id="traceCode">${lesson.trace.code.map((x,i)=>`<div data-line="${i}">${esc(x)||" "}</div>`).join("")}</div><div class="trace-controls"><button id="traceReset">Reset</button><button id="traceNext">Next step</button><button id="traceAuto">Auto run</button></div></div><div class="trace-state"><strong id="traceState">Ready</strong><p id="traceExplain">Press Next step to begin.</p></div></div></section>
<section class="lesson-section"><p class="section-label">QUICK REVISION</p><h2>Recall the essential ideas</h2><div class="revision-grid">${lesson.revision.map(x=>`<div><b>${esc(x[0])}</b><span>${esc(x[1])}</span></div>`).join("")}</div></section>
<section class="lesson-section interview"><p class="section-label">INTERVIEW QUESTIONS</p><h2>Explain, do not only define</h2>${lesson.interview.map(x=>`<details><summary>${esc(x.q)}</summary><p>${esc(x.a)}</p></details>`).join("")}</section>
<section class="lesson-section"><p class="section-label">EXTRA PRACTICE</p><h2>Build without copying the example</h2><div class="practice-grid">${lesson.practice.map((x,i)=>`<article class="practice-card"><span>CHALLENGE ${i+1}</span><h3>${esc(x.title)}</h3><p>${esc(x.prompt)}</p></article>`).join("")}</div></section>
<section class="lesson-section quiz"><p class="section-label">KNOWLEDGE CHECK</p><h2>Test the mental model</h2>${lesson.quiz.map((q,i)=>`<article class="quiz-question" data-question="${i}"><p>${i+1}. ${esc(q.q)}</p><div class="quiz-options">${q.options.map((o,j)=>`<button data-option="${j}">${esc(o)}</button>`).join("")}</div><div class="quiz-result" hidden></div></article>`).join("")}</section>
<section class="lesson-section"><p class="section-label">KEY TAKEAWAY</p><h2>${esc(lesson.takeaway)}</h2><button class="complete-button" id="completeLevel">Mark Level ${n} complete</button></section><nav class="lesson-nav">${n>1?`<a href="lesson.html?level=${n-1}">← Previous level</a>`:"<span></span>"}<a href="${n<6?`lesson.html?level=${n+1}`:"index.html#roadmap"}">${n<6?"Next level →":"Return to roadmap →"}</a></nav>`;initTrace();drawComplete()}
function drawComplete(){const done=JSON.parse(localStorage.getItem(KEY)||"[]"),b=document.getElementById("completeLevel");if(b)b.textContent=done.includes(n)?`✓ Level ${n} completed`:`Mark Level ${n} complete`}
let timer;function traceDraw(){document.querySelectorAll("[data-line]").forEach(x=>x.classList.remove("active"));const step=lesson.trace.steps[traceIndex];if(!step){document.getElementById("traceState").textContent="Trace complete";document.getElementById("traceExplain").textContent="Reset to follow it again.";document.getElementById("traceNext").disabled=true;document.getElementById("traceAuto").disabled=true;clearInterval(timer);return}document.querySelector(`[data-line="${step.line}"]`)?.classList.add("active");document.getElementById("traceState").textContent=step.state;document.getElementById("traceExplain").textContent=step.explain;traceIndex++}
function initTrace(){document.getElementById("traceNext").onclick=traceDraw;document.getElementById("traceReset").onclick=()=>{clearInterval(timer);traceIndex=0;document.querySelectorAll("[data-line]").forEach(x=>x.classList.remove("active"));document.getElementById("traceState").textContent="Ready";document.getElementById("traceExplain").textContent="Press Next step to begin.";document.getElementById("traceNext").disabled=false;document.getElementById("traceAuto").disabled=false};document.getElementById("traceAuto").onclick=()=>{clearInterval(timer);timer=setInterval(traceDraw,850)}}
document.addEventListener("click",async e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.copy!==undefined){try{await navigator.clipboard.writeText(b.dataset.copy);toast("Code copied")}catch{toast("Select the code manually")}}if(b.dataset.option!==undefined){const box=b.closest(".quiz-question"),i=+box.dataset.question,q=lesson.quiz[i],choice=+b.dataset.option;box.querySelectorAll("[data-option]").forEach((x,j)=>{x.disabled=true;if(j===q.answer)x.classList.add("correct");else if(j===choice)x.classList.add("wrong")});const r=box.querySelector(".quiz-result");r.hidden=false;r.textContent=`${choice===q.answer?"Correct.":"Not quite."} ${q.explanation}`}if(b.id==="completeLevel"){let done=JSON.parse(localStorage.getItem(KEY)||"[]");done=done.includes(n)?done.filter(x=>x!==n):[...done,n];localStorage.setItem(KEY,JSON.stringify(done));drawComplete()}if(b.id==="navToggle")document.getElementById("siteNav").classList.toggle("open")});function toast(s){const t=document.getElementById("toast");t.textContent=s;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1300)}
function sidebar(open){document.getElementById("sidebar").classList.toggle("open",open);document.getElementById("shade").hidden=!open}document.getElementById("lessonMenu").onclick=()=>sidebar(!document.getElementById("sidebar").classList.contains("open"));document.getElementById("shade").onclick=()=>sidebar(false);document.getElementById("levelSearch").oninput=e=>document.querySelectorAll("#levelNav a").forEach(a=>a.hidden=!a.textContent.toLowerCase().includes(e.target.value.toLowerCase()));window.addEventListener("scroll",()=>{const d=document.documentElement,max=d.scrollHeight-innerHeight;document.getElementById("readingBar").style.width=(max?scrollY/max*100:0)+"%"});nav();render();document.getElementById("year").textContent=new Date().getFullYear();
