(function(){
    "use strict";
    function hideResult(text){const result=document.getElementById("probExplorerResult"),message=document.getElementById("probExplorerMessage");if(result){result.hidden=true;}if(message){message.hidden=false;message.textContent=text||"Values are ready. Click Calculate Probability to display the result.";}}
    function probabilityText(value){return String(Math.round((value+Number.EPSILON)*1000000)/1000000);}
    function updateLabels(){const mode=document.getElementById("probabilityMode"),labelA=document.getElementById("probabilityLabelA"),labelB=document.getElementById("probabilityLabelB"),inputB=document.getElementById("probabilityValueB");if(!mode||!labelA||!labelB||!inputB){return;}inputB.disabled=false;if(mode.value==="equallyLikely"){labelA.textContent="Favourable outcomes";labelB.textContent="Total outcomes";}else if(mode.value==="complement"){labelA.textContent="P(A)";labelB.textContent="Not required";inputB.disabled=true;}else if(mode.value==="independentBoth"||mode.value==="independentAtLeastOne"){labelA.textContent="P(A)";labelB.textContent="P(B)";}else if(mode.value==="conditional"){labelA.textContent="P(A ∩ B)";labelB.textContent="P(B)";}else{labelA.textContent="Number of coin tosses";labelB.textContent="Not required";inputB.disabled=true;}hideResult();}
    function setSimulation(hidden,heads,tails){const bar=document.getElementById("probSimulationBar"),headsBar=document.getElementById("probHeadsBar"),tailsBar=document.getElementById("probTailsBar");if(!bar||!headsBar||!tailsBar){return;}bar.hidden=hidden;if(!hidden){const total=heads+tails,headPercent=total?heads/total*100:0;headsBar.style.width=headPercent+"%";tailsBar.style.width=(100-headPercent)+"%";headsBar.textContent="H: "+heads;tailsBar.textContent="T: "+tails;}}
    function calculate(){const mode=document.getElementById("probabilityMode"),inputA=document.getElementById("probabilityValueA"),inputB=document.getElementById("probabilityValueB"),result=document.getElementById("probExplorerResult"),message=document.getElementById("probExplorerMessage"),title=document.getElementById("probResultTitle"),number=document.getElementById("probResultNumber"),formula=document.getElementById("probResultFormula"),explanation=document.getElementById("probResultExplanation");if(!mode||!inputA||!inputB||!result||!message||!title||!number||!formula||!explanation){return;}const a=Number(inputA.value),b=Number(inputB.value);let probability;setSimulation(true,0,0);
        if(mode.value==="equallyLikely"){if(!Number.isInteger(a)||!Number.isInteger(b)||a<0||b<=0||a>b){hideResult("Enter whole-number outcomes with 0 ≤ favourable ≤ total and total greater than 0.");return;}probability=a/b;title.textContent="Equally Likely Probability";formula.textContent="P(A) = "+a+" / "+b+" = "+probabilityText(probability);explanation.textContent="The favourable outcomes were divided by all equally likely outcomes.";}
        else if(mode.value==="coinSimulation"){if(!Number.isInteger(a)||a<1||a>10000){hideResult("Enter a whole number of tosses from 1 to 10,000.");return;}let heads=0;for(let i=0;i<a;i++){if(Math.random()<0.5){heads++;}}const tails=a-heads;probability=heads/a;title.textContent="Coin-Toss Simulation";formula.textContent="Experimental P(head) = "+heads+" / "+a+" = "+probabilityText(probability);explanation.textContent="Theoretical P(head)=0.5. Experimental results vary, but usually move closer to 0.5 as trials increase.";setSimulation(false,heads,tails);}
        else{if(!Number.isFinite(a)||a<0||a>1){hideResult("Enter probability values from 0 to 1.");return;}if(mode.value!=="complement"&&(!Number.isFinite(b)||b<0||b>1)){hideResult("Enter probability values from 0 to 1.");return;}if(mode.value==="complement"){probability=1-a;title.textContent="Complement Probability";formula.textContent="1 − "+probabilityText(a)+" = "+probabilityText(probability);explanation.textContent="The event and its complement cover the complete sample space.";}else if(mode.value==="independentBoth"){probability=a*b;title.textContent="Both Independent Events";formula.textContent=probabilityText(a)+" × "+probabilityText(b)+" = "+probabilityText(probability);explanation.textContent="Independent probabilities multiply when both events must occur.";}else if(mode.value==="independentAtLeastOne"){probability=1-(1-a)*(1-b);title.textContent="At Least One Independent Event";formula.textContent="1 − (1−"+probabilityText(a)+")(1−"+probabilityText(b)+") = "+probabilityText(probability);explanation.textContent="The complement is that neither event occurs.";}else{if(b===0||a>b){hideResult("For conditional probability, P(B) must be greater than 0 and P(A ∩ B) cannot exceed P(B).");return;}probability=a/b;title.textContent="Conditional Probability";formula.textContent="P(A|B) = "+probabilityText(a)+" / "+probabilityText(b)+" = "+probabilityText(probability);explanation.textContent="The sample space is restricted to outcomes where B occurred.";}}
        number.textContent=probabilityText(probability)+"  ("+probabilityText(probability*100)+"%)";message.hidden=true;result.hidden=false;
    }
    function fillExample(button){const mode=document.getElementById("probabilityMode"),a=document.getElementById("probabilityValueA"),b=document.getElementById("probabilityValueB");if(!mode||!a||!b){return;}mode.value=button.dataset.mode;a.value=button.dataset.a;b.value=button.dataset.b;updateLabels();}
    function initialiseSolutions(){document.querySelectorAll(".solution-toggle").forEach(function(button){button.addEventListener("click",function(){const answer=document.getElementById(button.dataset.target);if(!answer){return;}const open=answer.hidden;answer.hidden=!open;button.setAttribute("aria-expanded",String(open));button.textContent=open?"Hide Solution":"Show Solution";});});}
    document.addEventListener("DOMContentLoaded",function(){const mode=document.getElementById("probabilityMode"),calculateButton=document.getElementById("calculateProbabilityButton");if(mode){mode.addEventListener("change",updateLabels);}if(calculateButton){calculateButton.addEventListener("click",calculate);}document.querySelectorAll(".explorer-example-button").forEach(function(button){button.addEventListener("click",function(){fillExample(button);});});["probabilityValueA","probabilityValueB"].forEach(function(id){const input=document.getElementById(id);if(input){input.addEventListener("input",function(){hideResult();});}});initialiseSolutions();updateLabels();const initial=document.getElementById("probExplorerMessage");if(initial){initial.textContent="Select a model or example, then click Calculate Probability.";}});
}());
