"use strict";
const { main, makeJava }=require("./helpers");
const T="Level 06 — Arrays & Matrices";
const e=(slug,title,body,out,concepts,extra={})=>makeJava({slug:`java-${slug}`,title:`${title} in Java`,topic:T,source:main(body,extra.imports||""),sampleOutput:out,concepts,...extra});
module.exports=[
 e("array-create-access","Create and Access an Array",'int[] values={10,20,30,40};\nSystem.out.println(values[0]+" "+values[values.length-1]);',"10 40",["Array","Indexing"]),
 e("array-traversal","Traverse an Array",'int[] values={2,4,6,8};\nfor(int value:values) System.out.print(value+" ");',"2 4 6 8",["Enhanced for","Traversal"]),
 e("array-sum-average","Find Array Sum and Average",'int[] values={10,20,30,40}; int sum=0;\nfor(int value:values) sum+=value;\nSystem.out.println(sum+" "+(sum/(double)values.length));',"100 25.0",["Accumulator","Average"]),
 e("array-min-max","Find Minimum and Maximum",'int[] values={7,2,9,4}; int min=values[0],max=values[0];\nfor(int value:values){ if(value<min)min=value; if(value>max)max=value; }\nSystem.out.println(min+" "+max);',"2 9",["Running minimum","Running maximum"]),
 e("reverse-array","Reverse an Array",'int[] values={1,2,3,4,5};\nfor(int i=values.length-1;i>=0;i--) System.out.print(values[i]+" ");',"5 4 3 2 1",["Reverse traversal","Index"]),
 e("copy-array","Copy an Array",'int[] original={3,6,9};\nint[] copy=java.util.Arrays.copyOf(original,original.length);\ncopy[0]=30;\nSystem.out.println(java.util.Arrays.toString(original));\nSystem.out.println(java.util.Arrays.toString(copy));',"[3, 6, 9]\n[30, 6, 9]",["Arrays.copyOf()","Independent copy"]),
 e("linear-search","Perform Linear Search",'int[] values={8,3,11,6}; int target=11,index=-1;\nfor(int i=0;i<values.length;i++) if(values[i]==target){index=i;break;}\nSystem.out.println(index);',"2",["Linear search","Sentinel result"],{time:"O(n)"}),
 e("binary-search","Perform Binary Search",'int[] values={2,5,8,12,16}; int target=12,low=0,high=values.length-1,result=-1;\nwhile(low<=high){int mid=low+(high-low)/2;if(values[mid]==target){result=mid;break;}if(values[mid]<target)low=mid+1;else high=mid-1;}\nSystem.out.println(result);',"3",["Binary search","Sorted array"],{difficulty:"Intermediate",time:"O(log n)",space:"O(1)"}),
 e("sort-array","Sort an Array",'int[] values={8,1,6,3};\njava.util.Arrays.sort(values);\nSystem.out.println(java.util.Arrays.toString(values));',"[1, 3, 6, 8]",["Arrays.sort()","Ascending order"],{time:"O(n log n)"}),
 e("second-largest-array","Find the Second Largest Distinct Value",'int[] values={9,2,7,9,5}; int largest=Integer.MIN_VALUE,second=Integer.MIN_VALUE;\nfor(int value:values){if(value>largest){second=largest;largest=value;}else if(value>second&&value!=largest)second=value;}\nSystem.out.println(second);',"7",["Distinct values","Two trackers"],{difficulty:"Intermediate"}),
 e("remove-array-duplicates","Remove Duplicates from an Array",'int[] values={3,1,3,2,1};\njava.util.Set<Integer> unique=new java.util.LinkedHashSet<>();\nfor(int value:values)unique.add(value);\nSystem.out.println(unique);',"[3, 1, 2]",["LinkedHashSet","Duplicate removal"],{imports:"import java.util.*;",space:"O(n)"}),
 e("rotate-array-left","Rotate an Array Left",'int[] values={1,2,3,4,5}; int first=values[0];\nfor(int i=0;i<values.length-1;i++)values[i]=values[i+1];\nvalues[values.length-1]=first;\nSystem.out.println(java.util.Arrays.toString(values));',"[2, 3, 4, 5, 1]",["Array rotation","Shifting"]),
 e("matrix-addition","Add Two Matrices",'int[][] a={{1,2},{3,4}},b={{5,6},{7,8}},sum=new int[2][2];\nfor(int i=0;i<2;i++)for(int j=0;j<2;j++)sum[i][j]=a[i][j]+b[i][j];\nfor(int[] row:sum)System.out.println(java.util.Arrays.toString(row));',"[6, 8]\n[10, 12]",["2D array","Matrix addition"],{time:"O(n²)",space:"O(n²)"}),
 e("matrix-transpose","Transpose a Matrix",'int[][] matrix={{1,2,3},{4,5,6}};\nfor(int column=0;column<3;column++){for(int row=0;row<2;row++)System.out.print(matrix[row][column]+" ");System.out.println();}',"1 4\n2 5\n3 6",["Transpose","Row-column exchange"],{time:"O(n²)"}),
 e("matrix-multiplication","Multiply Two Matrices",'int[][] a={{1,2},{3,4}},b={{2,0},{1,2}},result=new int[2][2];\nfor(int i=0;i<2;i++)for(int j=0;j<2;j++)for(int k=0;k<2;k++)result[i][j]+=a[i][k]*b[k][j];\nfor(int[] row:result)System.out.println(java.util.Arrays.toString(row));',"[4, 4]\n[10, 8]",["Matrix multiplication","Triple loop"],{difficulty:"Intermediate",time:"O(n³)",space:"O(n²)"})
];
