"use strict";
const { clean, makeJava }=require("./helpers");
const T="Level 09 — Classes, Objects & Constructors";
const e=(slug,title,source,out,concepts,extra={})=>makeJava({slug:`java-${slug}`,title:`${title} in Java`,topic:T,source:clean(source),sampleOutput:out,concepts,difficulty:"Intermediate",...extra});
module.exports=[
 e("class-object","Create a Class and Object",`class Student { String name; }\nclass Main { public static void main(String[] args) { Student student=new Student(); student.name="Asha"; System.out.println(student.name); } }`,"Asha",["class","Object"]),
 e("default-constructor","Use a Default Constructor",`class Course { String name="Java"; }\nclass Main { public static void main(String[] args) { Course course=new Course(); System.out.println(course.name); } }`,"Java",["Default constructor","Field"]),
 e("parameterized-constructor","Initialize with a Parameterized Constructor",`class Student { String name; int mark; Student(String name,int mark){this.name=name;this.mark=mark;} }\nclass Main { public static void main(String[] args){Student student=new Student("Ravi",91);System.out.println(student.name+" "+student.mark);} }`,"Ravi 91",["Constructor","this"]),
 e("constructor-overloading","Overload Constructors",`class Box { int length,width; Box(){this(1,1);} Box(int length,int width){this.length=length;this.width=width;} int area(){return length*width;} }\nclass Main { public static void main(String[] args){System.out.println(new Box().area()+" "+new Box(4,5).area());} }`,"1 20",["Constructor overloading","this()"]),
 e("instance-method","Define an Instance Method",`class Rectangle { int length=5,width=3; int area(){return length*width;} }\nclass Main { public static void main(String[] args){System.out.println(new Rectangle().area());} }`,"15",["Instance method","Object state"]),
 e("static-member","Use a Static Member",`class Student { static String college="CodeBhavya"; String name; Student(String name){this.name=name;} }\nclass Main { public static void main(String[] args){Student first=new Student("Asha");Student second=new Student("Ravi");System.out.println(first.name+" "+second.name+" "+Student.college);} }`,"Asha Ravi CodeBhavya",["static field","Shared state"]),
 e("encapsulation","Encapsulate a Field",`class Account { private double balance; Account(double balance){this.balance=balance;} void deposit(double amount){if(amount>0)balance+=amount;} double getBalance(){return balance;} }\nclass Main { public static void main(String[] args){Account account=new Account(1000);account.deposit(500);System.out.println(account.getBalance());} }`,"1500.0",["private","Getter","Validation"]),
 e("object-array","Create an Array of Objects",`class Student { String name; int mark; Student(String n,int m){name=n;mark=m;} }\nclass Main { public static void main(String[] args){Student[] students={new Student("Asha",82),new Student("Ravi",91)};for(Student s:students)System.out.println(s.name+" "+s.mark);} }`,"Asha 82\nRavi 91",["Object array","Enhanced for"],{time:"O(n)",space:"O(n)"}),
 e("object-composition","Build Objects with Composition",`class Address { String city; Address(String city){this.city=city;} }\nclass Student { String name; Address address; Student(String name,Address address){this.name=name;this.address=address;} }\nclass Main { public static void main(String[] args){Student student=new Student("Asha",new Address("Hyderabad"));System.out.println(student.name+" - "+student.address.city);} }`,"Asha - Hyderabad",["Composition","Has-a relationship"]),
 e("immutable-class","Create an Immutable Class",`final class Point { private final int x,y; Point(int x,int y){this.x=x;this.y=y;} int x(){return x;} int y(){return y;} }\nclass Main { public static void main(String[] args){Point point=new Point(3,4);System.out.println(point.x()+" "+point.y());} }`,"3 4",["final class","Immutability"],{difficulty:"Advanced"}),
 e("record-class","Use a Java Record",`record Student(String name,int mark) {}\nclass Main { public static void main(String[] args){Student student=new Student("Asha",92);System.out.println(student.name()+" "+student.mark());} }`,"Asha 92",["record","Accessor"],{difficulty:"Advanced"}),
 e("object-equality","Implement Object Equality",`import java.util.Objects;\nclass Student { int id; Student(int id){this.id=id;} public boolean equals(Object other){return other instanceof Student s&&id==s.id;} public int hashCode(){return Objects.hash(id);} }\nclass Main { public static void main(String[] args){System.out.println(new Student(7).equals(new Student(7)));} }`,"true",["equals()","hashCode()"],{difficulty:"Advanced"})
];
