"use strict";
const { clean, makeJava }=require("./helpers");
const T="Level 14 — File Handling & Serialization";
const e=(slug,title,source,out,concepts,extra={})=>makeJava({slug:`java-${slug}`,title:`${title} in Java`,topic:T,source:clean(source),sampleOutput:out,concepts,difficulty:"Intermediate",time:"O(n)",space:"O(n)",...extra});
module.exports=[
 e("write-read-text-file","Write and Read a Text File",`import java.nio.file.*;\nclass Main{public static void main(String[] args)throws Exception{Path path=Path.of("lesson.txt");Files.writeString(path,"Learn Java");System.out.println(Files.readString(path));}}`,"Learn Java",["Files.writeString()","Files.readString()"]),
 e("append-text-file","Append Text to a File",`import java.nio.file.*;\nclass Main{public static void main(String[] args)throws Exception{Path path=Path.of("notes.txt");Files.writeString(path,"C\\n");Files.writeString(path,"Java\\n",StandardOpenOption.APPEND);System.out.print(Files.readString(path));}}`,"C\nJava",["StandardOpenOption.APPEND","Path"]),
 e("buffered-file-reading","Read a File with BufferedReader",`import java.io.*;import java.nio.file.*;\nclass Main{public static void main(String[] args)throws Exception{Path path=Path.of("topics.txt");Files.writeString(path,"Basics\\nLoops\\nMethods\\n");try(BufferedReader reader=Files.newBufferedReader(path)){String line;while((line=reader.readLine())!=null)System.out.println(line);}}}`,"Basics\nLoops\nMethods",["BufferedReader","try-with-resources"],{space:"O(1)"}),
 e("buffered-file-writing","Write a File with BufferedWriter",`import java.io.*;import java.nio.file.*;\nclass Main{public static void main(String[] args)throws Exception{Path path=Path.of("marks.txt");try(BufferedWriter writer=Files.newBufferedWriter(path)){writer.write("Asha 92");writer.newLine();}System.out.print(Files.readString(path));}}`,"Asha 92",["BufferedWriter","newLine()"]),
 e("count-file-lines","Count Lines in a File",`import java.nio.file.*;\nclass Main{public static void main(String[] args)throws Exception{Path path=Path.of("data.txt");Files.writeString(path,"A\\nB\\nC\\n");try(var lines=Files.lines(path)){System.out.println(lines.count());}}}`,"3",["Files.lines()","Stream"],{space:"O(1)"}),
 e("list-directory-files","List Files in a Directory",`import java.nio.file.*;import java.util.*;\nclass Main{public static void main(String[] args)throws Exception{Path dir=Path.of("demo");Files.createDirectories(dir);Files.writeString(dir.resolve("a.txt"),"A");Files.writeString(dir.resolve("b.txt"),"B");try(var paths=Files.list(dir)){paths.map(p->p.getFileName().toString()).sorted().forEach(System.out::println);}}}`,"a.txt\nb.txt",["Files.list()","Directory"],{space:"O(n)"}),
 e("data-streams","Write and Read Primitive Data",`import java.io.*;\nclass Main{public static void main(String[] args)throws Exception{try(DataOutputStream out=new DataOutputStream(new FileOutputStream("score.dat"))){out.writeUTF("Asha");out.writeInt(92);}try(DataInputStream in=new DataInputStream(new FileInputStream("score.dat"))){System.out.println(in.readUTF()+" "+in.readInt());}}}`,"Asha 92",["DataOutputStream","DataInputStream"],{space:"O(1)"}),
 e("object-serialization","Serialize and Deserialize an Object",`import java.io.*;\nrecord Student(String name,int mark) implements Serializable{}\nclass Main{public static void main(String[] args)throws Exception{try(ObjectOutputStream out=new ObjectOutputStream(new FileOutputStream("student.dat"))){out.writeObject(new Student("Ravi",91));}try(ObjectInputStream in=new ObjectInputStream(new FileInputStream("student.dat"))){Student student=(Student)in.readObject();System.out.println(student.name()+" "+student.mark());}}}`,"Ravi 91",["Serializable","Object streams"],{difficulty:"Advanced",space:"O(1)"})
];
