"use strict";
const { clean, makeJava }=require("./helpers");
const T="Level 15 — Multithreading & Concurrency";
const e=(slug,title,source,out,concepts,extra={})=>makeJava({slug:`java-${slug}`,title:`${title} in Java`,topic:T,source:clean(source),sampleOutput:out,concepts,difficulty:"Advanced",...extra});
module.exports=[
 e("thread-class","Create a Thread by Extending Thread",`class Worker extends Thread{public void run(){System.out.println("Worker running");}}\nclass Main{public static void main(String[] args)throws Exception{Worker worker=new Worker();worker.start();worker.join();}}`,"Worker running",["Thread","start()"]),
 e("runnable-task","Create a Runnable Task",`class Main{public static void main(String[] args)throws Exception{Thread worker=new Thread(()->System.out.println("Task running"));worker.start();worker.join();}}`,"Task running",["Runnable","Lambda"]),
 e("thread-join","Wait for a Thread with join",`class Main{public static void main(String[] args)throws Exception{StringBuilder result=new StringBuilder();Thread worker=new Thread(()->result.append("Completed"));worker.start();worker.join();System.out.println(result);}}`,"Completed",["join()","Coordination"]),
 e("synchronized-counter","Protect a Shared Counter",`class Counter{private int value; synchronized void increment(){value++;}int value(){return value;}}\nclass Main{public static void main(String[] args)throws Exception{Counter counter=new Counter();Thread a=new Thread(()->{for(int i=0;i<1000;i++)counter.increment();});Thread b=new Thread(()->{for(int i=0;i<1000;i++)counter.increment();});a.start();b.start();a.join();b.join();System.out.println(counter.value());}}`,"2000",["synchronized","Race condition"],{time:"O(n)"}),
 e("atomic-counter","Update an AtomicInteger",`import java.util.concurrent.atomic.*;\nclass Main{public static void main(String[] args)throws Exception{AtomicInteger count=new AtomicInteger();Thread a=new Thread(()->{for(int i=0;i<500;i++)count.incrementAndGet();});Thread b=new Thread(()->{for(int i=0;i<500;i++)count.incrementAndGet();});a.start();b.start();a.join();b.join();System.out.println(count.get());}}`,"1000",["AtomicInteger","Lock-free update"],{time:"O(n)"}),
 e("executor-service","Run Tasks with ExecutorService",`import java.util.concurrent.*;\nclass Main{public static void main(String[] args)throws Exception{ExecutorService pool=Executors.newSingleThreadExecutor();Future<Integer> result=pool.submit(()->21*2);System.out.println(result.get());pool.shutdown();}}`,"42",["ExecutorService","Future"]),
 e("completable-future","Compose a CompletableFuture",`import java.util.concurrent.*;\nclass Main{public static void main(String[] args){CompletableFuture<Integer> future=CompletableFuture.completedFuture(20).thenApply(value->value+22);System.out.println(future.join());}}`,"42",["CompletableFuture","thenApply()"]),
 e("producer-consumer-queue","Use a BlockingQueue",`import java.util.concurrent.*;\nclass Main{public static void main(String[] args)throws Exception{BlockingQueue<String> queue=new ArrayBlockingQueue<>(2);Thread producer=new Thread(()->{try{queue.put("Java");}catch(InterruptedException e){Thread.currentThread().interrupt();}});producer.start();System.out.println(queue.take());producer.join();}}`,"Java",["BlockingQueue","Producer-consumer"])
];
