"use strict";
const { clean, makeJava }=require("./helpers");
const T="Level 17 — Data Structures & Algorithms in Java";
const e=(slug,title,source,out,concepts,extra={})=>makeJava({slug:`java-${slug}`,title:`${title} in Java`,topic:T,source:clean(source),sampleOutput:out,concepts,difficulty:"Advanced",...extra});
module.exports=[
 e("stack-arraydeque","Implement Stack Operations",`import java.util.*;class Main{public static void main(String[] args){Deque<Integer> stack=new ArrayDeque<>();stack.push(10);stack.push(20);stack.push(30);System.out.println(stack.pop()+" "+stack.peek());}}`,"30 20",["Stack","ArrayDeque"],{time:"O(1)",space:"O(n)"}),
 e("queue-arraydeque","Implement Queue Operations",`import java.util.*;class Main{public static void main(String[] args){Queue<String> queue=new ArrayDeque<>();queue.offer("A");queue.offer("B");queue.offer("C");System.out.println(queue.poll()+" "+queue.peek());}}`,"A B",["Queue","FIFO"],{time:"O(1)",space:"O(n)"}),
 e("singly-linked-list","Build a Singly Linked List",`class Node{int value;Node next;Node(int value){this.value=value;}}class Main{public static void main(String[] args){Node head=new Node(10);head.next=new Node(20);head.next.next=new Node(30);for(Node current=head;current!=null;current=current.next)System.out.print(current.value+" ");}}`,"10 20 30",["Node","Linked list"],{time:"O(n)",space:"O(n)"}),
 e("reverse-linked-list","Reverse a Singly Linked List",`class Node{int v;Node next;Node(int v){this.v=v;}}class Main{public static void main(String[] args){Node head=new Node(1);head.next=new Node(2);head.next.next=new Node(3);Node previous=null,current=head;while(current!=null){Node next=current.next;current.next=previous;previous=current;current=next;}for(Node n=previous;n!=null;n=n.next)System.out.print(n.v+" ");}}`,"3 2 1",["Pointer reversal","Linked list"],{time:"O(n)",space:"O(1)"}),
 e("balanced-parentheses","Check Balanced Parentheses",`import java.util.*;class Main{public static void main(String[] args){String text="{[()]}";Deque<Character> stack=new ArrayDeque<>();boolean valid=true;for(char ch:text.toCharArray()){if("({[".indexOf(ch)>=0)stack.push(ch);else{if(stack.isEmpty()){valid=false;break;}char open=stack.pop();if((open=='('&&ch!=')')||(open=='{'&&ch!='}')||(open=='['&&ch!=']')){valid=false;break;}}}System.out.println(valid&&stack.isEmpty());}}`,"true",["Stack","Matching pairs"],{time:"O(n)",space:"O(n)"}),
 e("insertion-sort","Implement Insertion Sort",`import java.util.*;class Main{public static void main(String[] args){int[] values={8,3,5,1};for(int i=1;i<values.length;i++){int key=values[i],j=i-1;while(j>=0&&values[j]>key){values[j+1]=values[j];j--;}values[j+1]=key;}System.out.println(Arrays.toString(values));}}`,"[1, 3, 5, 8]",["Insertion sort","Stable sort"],{time:"O(n²)",space:"O(1)"}),
 e("merge-sort","Implement Merge Sort",`import java.util.*;class Main{static void sort(int[] a,int l,int r){if(l>=r)return;int m=(l+r)/2;sort(a,l,m);sort(a,m+1,r);int[] temp=new int[r-l+1];int i=l,j=m+1,k=0;while(i<=m&&j<=r)temp[k++]=a[i]<=a[j]?a[i++]:a[j++];while(i<=m)temp[k++]=a[i++];while(j<=r)temp[k++]=a[j++];System.arraycopy(temp,0,a,l,temp.length);}public static void main(String[] args){int[] a={8,3,5,1,9};sort(a,0,a.length-1);System.out.println(Arrays.toString(a));}}`,"[1, 3, 5, 8, 9]",["Merge sort","Divide and conquer"],{time:"O(n log n)",space:"O(n)"}),
 e("quick-sort","Implement Quick Sort",`import java.util.*;class Main{static void sort(int[] a,int low,int high){if(low>=high)return;int pivot=a[high],i=low;for(int j=low;j<high;j++)if(a[j]<=pivot){int t=a[i];a[i]=a[j];a[j]=t;i++;}int t=a[i];a[i]=a[high];a[high]=t;sort(a,low,i-1);sort(a,i+1,high);}public static void main(String[] args){int[] a={7,2,9,4};sort(a,0,a.length-1);System.out.println(Arrays.toString(a));}}`,"[2, 4, 7, 9]",["Quick sort","Partition"],{time:"O(n log n) average",space:"O(log n) average"}),
 e("binary-search-tree","Build and Traverse a BST",`class Node{int v;Node left,right;Node(int v){this.v=v;}}class Main{static Node insert(Node root,int v){if(root==null)return new Node(v);if(v<root.v)root.left=insert(root.left,v);else root.right=insert(root.right,v);return root;}static void inorder(Node root){if(root!=null){inorder(root.left);System.out.print(root.v+" ");inorder(root.right);}}public static void main(String[] args){Node root=null;for(int v:new int[]{5,3,7,2,4})root=insert(root,v);inorder(root);}}`,"2 3 4 5 7",["BST","Inorder traversal"],{time:"O(n log n) average",space:"O(n)"}),
 e("tree-level-order","Traverse a Tree Level by Level",`import java.util.*;class Node{int v;Node left,right;Node(int v){this.v=v;}}class Main{public static void main(String[] args){Node root=new Node(1);root.left=new Node(2);root.right=new Node(3);root.left.left=new Node(4);Queue<Node> q=new ArrayDeque<>();q.offer(root);while(!q.isEmpty()){Node n=q.poll();System.out.print(n.v+" ");if(n.left!=null)q.offer(n.left);if(n.right!=null)q.offer(n.right);}}}`,"1 2 3 4",["BFS","Queue"],{time:"O(n)",space:"O(n)"}),
 e("graph-bfs","Traverse a Graph with BFS",`import java.util.*;class Main{public static void main(String[] args){List<List<Integer>> g=List.of(List.of(1,2),List.of(0,3),List.of(0,3),List.of(1,2));boolean[] seen=new boolean[4];Queue<Integer> q=new ArrayDeque<>();q.offer(0);seen[0]=true;while(!q.isEmpty()){int u=q.poll();System.out.print(u+" ");for(int v:g.get(u))if(!seen[v]){seen[v]=true;q.offer(v);}}}}`,"0 1 2 3",["Graph","Breadth-first search"],{time:"O(V + E)",space:"O(V)"}),
 e("graph-dfs","Traverse a Graph with DFS",`import java.util.*;class Main{static void dfs(int u,List<List<Integer>> g,boolean[] seen){seen[u]=true;System.out.print(u+" ");for(int v:g.get(u))if(!seen[v])dfs(v,g,seen);}public static void main(String[] args){List<List<Integer>> g=List.of(List.of(1,2),List.of(0,3),List.of(0,3),List.of(1,2));dfs(0,g,new boolean[4]);}}`,"0 1 3 2",["Graph","Depth-first search"],{time:"O(V + E)",space:"O(V)"}),
 e("dijkstra-shortest-path","Find Shortest Paths with Dijkstra",`import java.util.*;class Main{public static void main(String[] args){int[][] w={{0,4,1},{4,0,2},{1,2,0}};int[] d={0,999,999};boolean[] used=new boolean[3];for(int step=0;step<3;step++){int u=-1;for(int i=0;i<3;i++)if(!used[i]&&(u==-1||d[i]<d[u]))u=i;used[u]=true;for(int v=0;v<3;v++)if(w[u][v]>0)d[v]=Math.min(d[v],d[u]+w[u][v]);}System.out.println(Arrays.toString(d));}}`,"[0, 3, 1]",["Dijkstra","Relaxation"],{time:"O(V²)",space:"O(V)"}),
 e("heap-top-k","Find the Top K Values with a Heap",`import java.util.*;class Main{public static void main(String[] args){int[] values={7,2,9,4,8};int k=3;PriorityQueue<Integer> heap=new PriorityQueue<>();for(int value:values){heap.offer(value);if(heap.size()>k)heap.poll();}List<Integer> result=new ArrayList<>(heap);result.sort(Comparator.reverseOrder());System.out.println(result);}}`,"[9, 8, 7]",["Min-heap","Top K"],{time:"O(n log k)",space:"O(k)"}),
 e("union-find","Implement Disjoint Set Union",`class DSU{int[] parent,size;DSU(int n){parent=new int[n];size=new int[n];for(int i=0;i<n;i++){parent[i]=i;size[i]=1;}}int find(int x){return parent[x]==x?x:(parent[x]=find(parent[x]));}void union(int a,int b){a=find(a);b=find(b);if(a==b)return;if(size[a]<size[b]){int t=a;a=b;b=t;}parent[b]=a;size[a]+=size[b];}}class Main{public static void main(String[] args){DSU dsu=new DSU(5);dsu.union(0,1);dsu.union(1,2);System.out.println(dsu.find(0)==dsu.find(2));System.out.println(dsu.find(0)==dsu.find(4));}}`,"true\nfalse",["DSU","Path compression"],{time:"O(α(n)) amortized",space:"O(n)"})
];
