-- CodeBhavya C Coding Arena starter bank: 12 executable problems.
-- Three distinct problems for each company focus, with sample and hidden tests.

begin;

with problems(slug,title,difficulty,target_path,statement,input_format,output_format,constraints,examples,starter_code,points,time_limit) as (values
('c-sum-digits','Sum the Digits','beginner','general','Read a non-negative integer and print the sum of its decimal digits. Zero has digit sum zero.','One integer n.','Print one integer: the digit sum.',array['0 <= n <= 10^18'],jsonb_build_array(jsonb_build_object('input','5029','output','16')),jsonb_build_object('c',E'#include <stdio.h>\n\nint main(void) {\n    unsigned long long n;\n    scanf("%llu", &n);\n    // Write your solution\n    return 0;\n}\n'),100,2),
('c-reverse-array','Reverse an Array','beginner','general','Read n integers and print them in reverse order on one line, separated by one space. Do not print an extra space after the final value.','First line n. Second line n integers.','The values in reverse order.',array['1 <= n <= 1000','-10^9 <= value <= 10^9'],jsonb_build_array(jsonb_build_object('input',E'5\n1 4 7 9 2','output','2 9 7 4 1')),jsonb_build_object('c',E'#include <stdio.h>\n\nint main(void) {\n    int n;\n    scanf("%d", &n);\n    // Read and reverse the array\n    return 0;\n}\n'),100,2),
('c-second-largest-distinct','Second Largest Distinct Value','intermediate','general','Print the second largest distinct integer in the array. If fewer than two distinct values exist, print NA.','First line n. Second line n integers.','The second largest distinct value, or NA.',array['1 <= n <= 100000','Values fit in signed int'],jsonb_build_array(jsonb_build_object('input',E'6\n5 1 5 3 9 9','output','5')),jsonb_build_object('c',E'#include <stdio.h>\n#include <limits.h>\n\nint main(void) {\n    int n;\n    scanf("%d", &n);\n    // Track two distinct maximum values\n    return 0;\n}\n'),150,2),
('c-count-vowels-line','Count Vowels in a Line','beginner','service','Read one complete line and count English vowels, ignoring letter case.','One line containing at most 1000 characters.','Print the vowel count.',array['Input may contain spaces','Vowels are a,e,i,o,u in either case'],jsonb_build_array(jsonb_build_object('input','Code Bhavya','output','4')),jsonb_build_object('c',E'#include <stdio.h>\n#include <ctype.h>\n\nint main(void) {\n    char line[1002];\n    fgets(line, sizeof line, stdin);\n    // Count vowels\n    return 0;\n}\n'),100,2),
('c-most-frequent-letter','Most Frequent Lowercase Letter','intermediate','service','Read a lowercase word and print the most frequent letter and its frequency. If frequencies tie, print the alphabetically smallest letter.','One lowercase word without spaces.','Print: letter frequency',array['1 <= length <= 100000','Only a through z'],jsonb_build_array(jsonb_build_object('input','banana','output','a 3')),jsonb_build_object('c',E'#include <stdio.h>\n\nint main(void) {\n    char word[100001];\n    int frequency[26] = {0};\n    scanf("%100000s", word);\n    // Count and choose the answer\n    return 0;\n}\n'),150,2),
('c-matrix-diagonal-difference','Matrix Diagonal Difference','intermediate','service','For an n by n integer matrix, print the absolute difference between the main-diagonal sum and secondary-diagonal sum.','First line n, followed by n rows of n integers.','One non-negative integer.',array['1 <= n <= 500','Each value is between -10^6 and 10^6'],jsonb_build_array(jsonb_build_object('input',E'3\n1 2 3\n4 5 6\n9 8 9','output','2')),jsonb_build_object('c',E'#include <stdio.h>\n#include <stdlib.h>\n\nint main(void) {\n    int n;\n    scanf("%d", &n);\n    // Accumulate both diagonals while reading\n    return 0;\n}\n'),150,2),
('c-pair-sum-sorted','Pair Sum in Sorted Data','intermediate','product','Given a sorted array and target, print the zero-based indexes of the first pair found by the two-pointer method whose values sum to target. Print -1 if no pair exists.','First line: n target. Second line: n sorted integers.','Two indexes separated by one space, or -1.',array['2 <= n <= 100000','Array is sorted in nondecreasing order'],jsonb_build_array(jsonb_build_object('input',E'6 11\n1 2 4 7 8 12','output','2 3')),jsonb_build_object('c',E'#include <stdio.h>\n\nint main(void) {\n    int n; long long target;\n    scanf("%d %lld", &n, &target);\n    // Read values and use two pointers\n    return 0;\n}\n'),150,2),
('c-balanced-brackets','Balanced Brackets','advanced','product','Determine whether a string containing only (), [] and {} is correctly balanced and nested. Print YES or NO.','One bracket string without spaces.','YES when balanced; otherwise NO.',array['1 <= length <= 100000','Input contains only bracket characters'],jsonb_build_array(jsonb_build_object('input','{[()]}','output','YES'),jsonb_build_object('input','([)]','output','NO')),jsonb_build_object('c',E'#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    char text[100001], stack[100001];\n    scanf("%100000s", text);\n    // Implement a stack\n    return 0;\n}\n'),200,2),
('c-maximum-subarray-sum','Maximum Subarray Sum','advanced','product','Print the maximum possible sum of a non-empty contiguous subarray.','First line n. Second line n integers.','One integer: the maximum contiguous sum.',array['1 <= n <= 100000','-10^9 <= value <= 10^9','The result fits signed 64-bit integer'],jsonb_build_array(jsonb_build_object('input',E'8\n-2 -3 4 -1 -2 1 5 -3','output','7')),jsonb_build_object('c',E'#include <stdio.h>\n\nint main(void) {\n    int n;\n    scanf("%d", &n);\n    // Use a 64-bit running and best sum\n    return 0;\n}\n'),200,2),
('c-count-above-mean','Count Values Above the Mean','beginner','ai','Read n real values and print how many are strictly greater than their arithmetic mean.','First line n. Second line n real values.','One integer count.',array['1 <= n <= 10000','Values fit in double'],jsonb_build_array(jsonb_build_object('input',E'5\n1 2 3 9 10','output','2')),jsonb_build_object('c',E'#include <stdio.h>\n\nint main(void) {\n    int n;\n    scanf("%d", &n);\n    // Store values, compute mean, then count\n    return 0;\n}\n'),100,2),
('c-min-max-normalize','Min-Max Normalize','intermediate','ai','Normalize each value using (x-min)/(max-min) and print values with exactly two digits after the decimal point, separated by spaces. If all values are equal, print 0.00 for every value.','First line n. Second line n real values.','n normalized values.',array['1 <= n <= 1000','Values fit in double'],jsonb_build_array(jsonb_build_object('input',E'4\n10 20 30 40','output','0.00 0.33 0.67 1.00')),jsonb_build_object('c',E'#include <stdio.h>\n\nint main(void) {\n    int n;\n    scanf("%d", &n);\n    // Find min and max, then normalize\n    return 0;\n}\n'),150,2),
('c-confusion-matrix-metrics','Precision and Recall from Counts','advanced','ai','Read TP, FP and FN as non-negative integers. Print precision and recall with exactly three digits after the decimal point. When a denominator is zero, print 0.000 for that metric.','Three integers: TP FP FN.','Print: precision recall',array['0 <= TP,FP,FN <= 10^9'],jsonb_build_array(jsonb_build_object('input','80 20 10','output','0.800 0.889')),jsonb_build_object('c',E'#include <stdio.h>\n\nint main(void) {\n    long long tp, fp, fn;\n    scanf("%lld %lld %lld", &tp, &fp, &fn);\n    // Compute both metrics safely\n    return 0;\n}\n'),200,2)
), upserted as (
 insert into public.coding_problems(slug,title,topic,difficulty,target_path,statement,input_format,output_format,constraints,examples,starter_code,points,time_limit_seconds,is_published,updated_at)
 select slug,title,'c',difficulty,target_path,statement,input_format,output_format,constraints,examples,starter_code,points,time_limit,true,now() from problems
 on conflict(slug) do update set title=excluded.title,difficulty=excluded.difficulty,target_path=excluded.target_path,statement=excluded.statement,input_format=excluded.input_format,output_format=excluded.output_format,constraints=excluded.constraints,examples=excluded.examples,starter_code=excluded.starter_code,points=excluded.points,time_limit_seconds=excluded.time_limit_seconds,is_published=true,updated_at=now()
 returning id,slug
), tests(slug,position,stdin,expected,is_sample) as (values
('c-sum-digits',1,'5029','16',true),('c-sum-digits',2,'0','0',false),('c-sum-digits',3,'999999','54',false),('c-sum-digits',4,'1000000000000000000','1',false),
('c-reverse-array',1,E'5\n1 4 7 9 2','2 9 7 4 1',true),('c-reverse-array',2,E'1\n-8','-8',false),('c-reverse-array',3,E'4\n0 0 1 2','2 1 0 0',false),('c-reverse-array',4,E'3\n-1 -2 -3','-3 -2 -1',false),
('c-second-largest-distinct',1,E'6\n5 1 5 3 9 9','5',true),('c-second-largest-distinct',2,E'4\n7 7 7 7','NA',false),('c-second-largest-distinct',3,E'5\n-8 -2 -3 -2 -9','-3',false),('c-second-largest-distinct',4,E'2\n1 2','1',false),
('c-count-vowels-line',1,'Code Bhavya','4',true),('c-count-vowels-line',2,'rhythm','0',false),('c-count-vowels-line',3,'AEIOUaeiou','10',false),('c-count-vowels-line',4,'A useful coding interview','10',false),
('c-most-frequent-letter',1,'banana','a 3',true),('c-most-frequent-letter',2,'abcd','a 1',false),('c-most-frequent-letter',3,'zzzyyy','y 3',false),('c-most-frequent-letter',4,'mississippi','i 4',false),
('c-matrix-diagonal-difference',1,E'3\n1 2 3\n4 5 6\n9 8 9','2',true),('c-matrix-diagonal-difference',2,E'1\n-7','0',false),('c-matrix-diagonal-difference',3,E'2\n1 2\n3 4','0',false),('c-matrix-diagonal-difference',4,E'3\n11 2 4\n4 5 6\n10 8 -12','15',false),
('c-pair-sum-sorted',1,E'6 11\n1 2 4 7 8 12','2 3',true),('c-pair-sum-sorted',2,E'4 100\n1 2 3 4','-1',false),('c-pair-sum-sorted',3,E'5 0\n-5 -2 0 2 8','1 3',false),('c-pair-sum-sorted',4,E'2 10\n5 5','0 1',false),
('c-balanced-brackets',1,'{[()]}','YES',true),('c-balanced-brackets',2,'([)]','NO',true),('c-balanced-brackets',3,'(','NO',false),('c-balanced-brackets',4,'()[]{}','YES',false),('c-balanced-brackets',5,'{{[[(())]]}}','YES',false),
('c-maximum-subarray-sum',1,E'8\n-2 -3 4 -1 -2 1 5 -3','7',true),('c-maximum-subarray-sum',2,E'3\n-8 -2 -5','-2',false),('c-maximum-subarray-sum',3,E'5\n1 2 3 4 5','15',false),('c-maximum-subarray-sum',4,E'1\n-9','-9',false),
('c-count-above-mean',1,E'5\n1 2 3 9 10','2',true),('c-count-above-mean',2,E'4\n5 5 5 5','0',false),('c-count-above-mean',3,E'3\n-2 0 2','1',false),('c-count-above-mean',4,E'1\n100','0',false),
('c-min-max-normalize',1,E'4\n10 20 30 40','0.00 0.33 0.67 1.00',true),('c-min-max-normalize',2,E'3\n5 5 5','0.00 0.00 0.00',false),('c-min-max-normalize',3,E'2\n-5 5','0.00 1.00',false),('c-min-max-normalize',4,E'5\n0 1 2 3 4','0.00 0.25 0.50 0.75 1.00',false),
('c-confusion-matrix-metrics',1,'80 20 10','0.800 0.889',true),('c-confusion-matrix-metrics',2,'0 0 0','0.000 0.000',false),('c-confusion-matrix-metrics',3,'5 0 5','1.000 0.500',false),('c-confusion-matrix-metrics',4,'0 5 10','0.000 0.000',false)
)
insert into public.coding_test_cases(problem_id,position,stdin,expected_output,is_sample)
select u.id,t.position,t.stdin,t.expected,t.is_sample from tests t join upserted u using(slug)
on conflict(problem_id,position) do update set stdin=excluded.stdin,expected_output=excluded.expected_output,is_sample=excluded.is_sample;

commit;

select target_path,count(*) from public.coding_problems where topic='c' and is_published=true group by target_path order by target_path;
