-- CodeBhavya C Placement MCQ bank: 80 distinct questions.
-- 20 per company focus. Balanced difficulty always supports an exact 20-question quiz.
-- Difficulty-specific quiz sizes are enabled by the page only when enough unseen questions exist.

begin;

with seed(target_path,difficulty,slug,subtopic,question,a,b,c,d,correct,explanation,rule) as (values
-- GENERAL PLACEMENT: 20
('general','beginner','c-gen-01','Strings','For char s[]="code"; what is sizeof(s)?','4','5','Size of a pointer','Undefined','B','The array contains four visible characters and the terminating null character, so its size is 5 bytes.','Include the null terminator when sizeof is applied to a string-initialized array.'),
('general','beginner','c-gen-02','Arrays','What is the last valid index of int a[8]?','6','7','8','9','B','A zero-based array of eight elements uses indexes 0 through 7.','For n elements, valid zero-based indexes are 0 through n-1.'),
('general','beginner','c-gen-03','Input','Which argument correctly reads an integer x with scanf?','scanf("%d", x)','scanf("%d", &x)','scanf(x, "%d")','scanf("%i", *x)','B','scanf needs the address of x so it can store the converted integer.','Pass an address to scanf for ordinary scalar output variables.'),
('general','beginner','c-gen-04','Arithmetic','What is the value of 7/2 when both operands are int?','3','3.5','4','Undefined','A','Integer division discards the fractional part, producing 3.','When both operands are integers, C performs integer division.'),
('general','beginner','c-gen-05','Loops','How many times does for(i=0;i<5;i++) execute its body?','4','5','6','It never stops','B','The body executes for i values 0,1,2,3 and 4: five iterations.','Count the values satisfying the condition before the update.'),
('general','beginner','c-gen-06','Functions','What is the main purpose of a function prototype?','Allocate heap memory','Declare parameter and return types before use','Execute the function','Create a loop','B','A prototype tells the compiler the function signature so calls can be type-checked.','Declare a function signature before calling the function.'),
('general','beginner','c-gen-07','Characters','Which format specifier prints a char value as a character?','%d','%s','%c','%f','C','%c converts an integer character code to its character representation.','Match printf conversion specifiers to the promoted argument type and intended display.'),
('general','intermediate','c-gen-08','Short-circuiting','If x is 0, what happens in x!=0 && 10/x>1?','Division by zero','The right side is skipped and the expression is false','The expression is true','Compilation fails','B','A false left operand determines &&, so the division is not evaluated.','Use && short-circuit order when the left condition protects the right expression.'),
('general','intermediate','c-gen-09','Storage duration','What happens to a static local variable between function calls?','It is recreated with an unknown value','It retains its value','It becomes visible in every file','It moves to the caller stack','B','A static local has local scope but static storage duration and therefore retains its value.','Separate a variable name’s scope from its storage lifetime.'),
('general','intermediate','c-gen-10','Pointers','Given int x=9; int *p=&x; what is *p?','The address of x','9','The address of p','Undefined','B','p stores x’s address and dereferencing p reads x’s value, 9.','A pointer stores an address; dereferencing accesses the pointed-to object.'),
('general','intermediate','c-gen-11','Functions','C function arguments are normally passed using which mechanism?','Pass by value','Pass by reference','Pass by name','Pass by result','A','C copies each argument value into its parameter, including when that value is a pointer.','C is pass-by-value; pointers allow access to caller-owned objects.'),
('general','intermediate','c-gen-12','Switch','What normally happens when a matching case has no break?','Only that case executes','Execution falls through later cases','The switch repeats','The program must crash','B','Control continues into subsequent case statements until it exits the switch.','Use break when fall-through is not deliberate.'),
('general','intermediate','c-gen-13','Structures','If p is a pointer to a struct Student, how is member age accessed?','p.age','p->age','*p.age','p::age','B','The arrow operator combines dereferencing a structure pointer with member selection.','Use dot for a structure object and arrow for a pointer to one.'),
('general','intermediate','c-gen-14','Files','Which fopen mode opens a text file for reading without creating it?','"r"','"w"','"a"','"x"','A','Mode r opens an existing file for reading and fails if it does not exist.','Choose fopen mode from the required reading, writing, appending and creation behavior.'),
('general','advanced','c-gen-15','EOF','Why should the result of fgetc be stored in int instead of char?','int is always faster','int can represent every unsigned-char value plus EOF','char cannot store letters','fgetc returns a pointer','B','The return type must distinguish all byte values from the separate EOF marker.','Store fgetc results in int and test EOF before converting to char.'),
('general','advanced','c-gen-16','Dynamic memory','Which expression correctly allocates n integers for int *p?','malloc(n)','malloc(sizeof p)','malloc(n*sizeof *p)','malloc(sizeof n)','C','n*sizeof *p reserves space for n objects of the pointed-to type.','Allocate element count multiplied by element size.'),
('general','advanced','c-gen-17','Array parameters','Inside void f(int a[]), what does sizeof(a) normally measure?','The complete caller array','The size of an int pointer','The number of initialized elements','A compile-time error','B','An array parameter is adjusted to pointer type, so sizeof(a) measures the pointer.','Pass the array length separately; a function parameter does not retain array extent.'),
('general','advanced','c-gen-18','Recursion','What is essential for a terminating recursive function?','A global variable','A reachable base case and progress toward it','A switch statement','Dynamic allocation','B','Valid calls must eventually reach a stopping condition through a smaller or simpler subproblem.','Prove both the base case and guaranteed progress toward it.'),
('general','advanced','c-gen-19','Null pointers','What is safe to do with a null pointer?','Dereference it','Pass it to free','Write through it','Read the pointed value','B','free(NULL) is defined to do nothing; dereferencing a null pointer is invalid.','Test pointer validity before dereferencing; free safely accepts NULL.'),
('general','advanced','c-gen-20','Operators','How does logical && differ from bitwise & for integer operands?','They are identical','&& produces a truth value and short-circuits; & combines bits','& short-circuits but && does not','&& works only on pointers','B','Logical AND evaluates truth and may skip its right operand; bitwise AND combines corresponding bits.','Choose logical operators for conditions and bitwise operators for bit manipulation.'),

-- SERVICE-BASED COMPANY: 20
('service','beginner','c-svc-01','Output tracing','What is printed by int x=3; printf("%d", ++x);?','3','4','5','Undefined','B','Prefix increment changes x to 4 before its value is used.','For prefix increment, modify first and then use the new value.'),
('service','beginner','c-svc-02','Conditions','Which value is considered false in a C if condition?','-1','0','1','Any nonzero value','B','Integer zero is false; nonzero integer values are true.','In C conditions, zero is false and nonzero is true.'),
('service','beginner','c-svc-03','Loops','Which loop always executes its body at least once?','for','while','do-while','None','C','do-while tests its condition after the first body execution.','Choose a post-test loop when one execution is required before checking.'),
('service','beginner','c-svc-04','Arrays','What initializes every element of int a[5]={0};?','Only a[0] becomes zero','All five elements become zero','No element is initialized','Compilation fails','B','The explicit first zero is followed by zero-initialization of all remaining elements.','Partial aggregate initialization zero-initializes unspecified elements.'),
('service','beginner','c-svc-05','Strings','Which function returns the number of characters before the null terminator?','sizeof','strlen','strcpy','strcmp','B','strlen counts characters until but not including the terminating null character.','Use strlen for current string length and sizeof only for object size.'),
('service','beginner','c-svc-06','Control flow','What does continue do inside a loop?','Ends the program','Ends the loop','Skips to the next iteration','Restarts main','C','continue skips the remaining body statements and proceeds with the next iteration step.','Distinguish continue from break: skip an iteration versus exit the loop.'),
('service','beginner','c-svc-07','Functions','What return type is used for a function that returns no value?','null','empty','void','none','C','void declares that the function does not return a value to its caller.','Use void when a function performs work without producing a return value.'),
('service','intermediate','c-svc-08','Debugging','Why is for(i=0;i<=n;i++) unsafe for an array of n elements?','It misses index zero','It accesses index n','It executes only once','It cannot compile','B','The valid indexes are 0 through n-1, so index n is outside the array.','Write the valid index range before selecting the loop boundary.'),
('service','intermediate','c-svc-09','Output tracing','What is printed by int a=5,b=2; printf("%d",a%b);?','0','1','2','2.5','B','5 divided by 2 leaves a remainder of 1.','The remainder operator returns what remains after integer division.'),
('service','intermediate','c-svc-10','Strings','What must destination provide before strcpy(destination,source)?','Only a null pointer','Enough writable space for source and its terminator','A read-only literal','The same address as source','B','strcpy does not allocate or check space, so the caller must provide a sufficient writable destination.','Reserve destination capacity including the terminating null character.'),
('service','intermediate','c-svc-11','Pointers','After int *p=NULL;, which check should precede *p?','if(*p)','if(p!=NULL)','if(&p)','if(sizeof p)','B','The pointer value itself must be checked before dereferencing it.','Validate a pointer before accessing the object it may identify.'),
('service','intermediate','c-svc-12','Input','Why can scanf("%s",name) be unsafe without a width?','It reads only numbers','Input may exceed the destination array','It always returns EOF','It adds two terminators','B','Unbounded %s can write past the destination buffer.','Limit input to destination capacity or use a bounded line-input method.'),
('service','intermediate','c-svc-13','Scope','What happens when an inner block declares int x with the same name as an outer x?','Both declarations become invalid','The inner x shadows the outer x in that block','The values automatically synchronize','The outer x is deleted','B','Name lookup in the inner block selects the nearer declaration.','Avoid accidental shadowing when both values must remain clear.'),
('service','intermediate','c-svc-14','Files','What does fopen return when opening fails?','EOF','NULL','0 bytes','An empty FILE object','B','fopen signals failure with a null pointer.','Check the FILE pointer before any read or write operation.'),
('service','advanced','c-svc-15','Undefined behaviour','Why is printf("%d %d",i++,i++) invalid reasoning material?','printf cannot print two integers','The modifications of i are unsequenced','Increment works only once','The format requires long','B','The two unsequenced modifications of i create undefined behavior, so no portable output exists.','Never predict a value for code whose side effects are unsequenced.'),
('service','advanced','c-svc-16','Memory','What defect results from using memory after free(p)?','Memory leak only','Use-after-free','Integer overflow','Stack underflow','B','The object lifetime ended at free, so later access through p is invalid.','After freeing, stop using aliases and clear owning pointers when helpful.'),
('service','advanced','c-svc-17','Linkage','What does static on a file-scope function normally provide?','External visibility','Internal linkage within that source file','Recursive execution','Heap allocation','B','The function name is restricted to the translation unit.','Use file-scope static to keep private implementation names internal.'),
('service','advanced','c-svc-18','Preprocessor','Why should a macro argument generally be parenthesized in its replacement text?','To allocate memory','To preserve intended operator precedence','To create a function pointer','To disable expansion','B','Parentheses prevent surrounding operators from changing how the substituted expression groups.','Parenthesize macro parameters and the complete replacement expression.'),
('service','advanced','c-svc-19','Structures','What may cause sizeof(struct S) to exceed the sum of its member sizes?','Recursion','Alignment padding','String termination','File buffering','B','The implementation may insert padding so members and arrays of the structure satisfy alignment requirements.','Do not assume a packed structure layout without an explicit supported mechanism.'),
('service','advanced','c-svc-20','Error handling','What should a program do after malloc returns NULL?','Dereference it once','Handle allocation failure before use','Call strlen on it','Assume zeroed memory','B','A null return means no allocation was obtained and dereferencing it is invalid.','Check allocation results and follow a defined cleanup or failure path.'),

-- PRODUCT-BASED COMPANY: 20
('product','beginner','c-prd-01','Complexity','What is the time complexity of one loop that visits n array elements once?','O(1)','O(log n)','O(n)','O(n²)','C','The work grows in direct proportion to the number of elements visited.','Count how many times the dominant operation executes.'),
('product','beginner','c-prd-02','Memory model','Which storage normally has automatic lifetime tied to a function call?','A static local','An ordinary local variable','A string literal','A global variable','B','An ordinary block local is created on entry and its lifetime ends when the block exits.','Separate automatic, static and allocated storage duration.'),
('product','beginner','c-prd-03','Pointers','If p points to a[0], what does p+1 point to?','The next byte always','a[1]','The pointer variable p itself','The last element','B','Pointer arithmetic advances by the size of the pointed-to element.','Pointer addition is scaled by the pointed-to type.'),
('product','beginner','c-prd-04','Binary data','Which type is intended to store object sizes returned by sizeof?','char','float','size_t','FILE','C','sizeof returns size_t, an unsigned integer type capable of representing object sizes.','Use size_t for object sizes and array indexes derived from sizeof.'),
('product','beginner','c-prd-05','API design','Which declaration makes a function promise not to modify characters through p?','char *p','const char *p','char const p','static char p','B','const char * allows the pointer to change while prohibiting modification through it.','Place const according to what the interface must protect.'),
('product','beginner','c-prd-06','Sorting','Binary search requires which precondition?','The array must be sorted according to the search order','All values must be unique','The array must be global','The size must be a power of two','A','Binary search discards halves using ordering, which is valid only on sorted data.','State algorithm preconditions before discussing complexity.'),
('product','beginner','c-prd-07','Integer representation','For unsigned integers, overflow is defined to wrap modulo what?','The maximum value','2 raised to the type width','10','It is always undefined','B','Unsigned arithmetic is performed modulo one more than the maximum value, normally 2^width.','Distinguish defined unsigned wraparound from signed overflow.'),
('product','intermediate','c-prd-08','Undefined behaviour','What is the status of signed integer overflow in C?','Guaranteed wraparound','Undefined behavior','Guaranteed saturation','Compile-time error only','B','The C language does not define a result for signed overflow.','Check bounds or use a suitable wider/unsigned design before overflowing signed values.'),
('product','intermediate','c-prd-09','Aliasing','Why can returning the address of an ordinary local variable be wrong?','Local addresses are always null','The object lifetime ends when the function returns','Pointers cannot be returned','The address becomes global','B','The returned pointer becomes dangling after the automatic local object ceases to exist.','Never return a pointer to an object whose lifetime has ended.'),
('product','intermediate','c-prd-10','Reallocation','What must code do with the result of realloc to avoid losing the original block on failure?','Assign directly to the only pointer','Store it in a temporary pointer first','Always call free before realloc','Convert it to int','B','If realloc fails it returns NULL and leaves the original block allocated, so a temporary preserves its address.','Use a temporary for realloc and replace the owner only after success.'),
('product','intermediate','c-prd-11','Complexity','Two nested loops each execute n times. What is the usual time complexity?','O(log n)','O(n)','O(n log n)','O(n²)','D','The inner work executes n times for each of n outer iterations.','Multiply dependent or full nested iteration counts.'),
('product','intermediate','c-prd-12','Bit operations','What does x & (x-1) do for a positive integer x?','Sets every bit','Clears the lowest set bit','Shifts right one position','Makes x negative','B','Subtracting one flips bits through the lowest set bit, and AND clears that bit.','Trace bit patterns instead of treating bitwise operators as logical operators.'),
('product','intermediate','c-prd-13','Function pointers','What does int (*fp)(int) declare?','A function returning int pointer','A pointer to a function taking int and returning int','An array of functions','An integer named fp','B','Parentheses make fp a pointer whose pointed-to function has the stated signature.','Read complex declarations outward from the identifier.'),
('product','intermediate','c-prd-14','Data structures','Why may a contiguous array outperform a linked list during sequential traversal?','Arrays use recursion','Better cache locality','Linked lists cannot store integers','Arrays never allocate memory','B','Nearby array elements occupy nearby memory and make effective use of cache lines.','Include locality and allocation overhead when comparing real data structures.'),
('product','advanced','c-prd-15','Concurrency','Why is volatile not a replacement for a mutex?','volatile makes data constant','It does not provide atomicity or inter-thread synchronization','It allocates too much memory','It disables threads','B','volatile affects certain accesses but does not create atomic operations or the required happens-before relationship.','Use language/platform synchronization primitives for shared concurrent state.'),
('product','advanced','c-prd-16','Pointer rules','When is subtracting two pointers defined?','Whenever their numeric addresses differ','When both point into the same array object or one past it','Only when both are null','Only for char pointers','B','Pointer subtraction is defined within one array object and yields an element distance.','Apply pointer arithmetic only within its permitted array object.'),
('product','advanced','c-prd-17','Memory safety','Why can memcpy be wrong when source and destination overlap?','It always adds a terminator','Its behavior is undefined for overlapping regions','It sorts the bytes','It frees the source','B','memcpy assumes non-overlap; memmove handles overlap safely.','Choose memmove when ranges may overlap.'),
('product','advanced','c-prd-18','API contracts','What does restrict communicate for a pointer parameter?','The pointer is read-only','Access through that pointer is not aliased in the promised scope','The pointer is static','The pointer cannot be null','B','restrict is an aliasing promise that may enable optimization; breaking the promise makes behavior undefined.','Use restrict only when the caller can satisfy the non-aliasing contract.'),
('product','advanced','c-prd-19','Parsing','Why is atoi usually weaker than strtol for validated input?','atoi cannot parse digits','atoi provides no reliable end-position or overflow reporting','strtol returns a string','atoi requires a file','B','strtol exposes where parsing stopped and reports range errors through errno.','Use conversion APIs that let you distinguish valid input from failure.'),
('product','advanced','c-prd-20','Design','What is the safest growth check before allocating count*size bytes?','Check the product after it overflows','Verify count <= SIZE_MAX/size before multiplication','Convert both values to float','Assume malloc detects every overflow','B','The division check proves the multiplication is representable before calculating it.','Validate size multiplication before allocation to prevent undersized buffers.'),

-- AI / DATA COMPANY: 20
('ai','beginner','c-ai-01','Numeric types','Which type normally provides more precision: float or double?','float','double','They are required to be identical','char','B','double provides at least as much precision and range as float and commonly more.','Choose numeric types according to required range and precision.'),
('ai','beginner','c-ai-02','Arrays','For a row-major matrix with cols columns, what is the flat index of row r, column c?','r+c','r*cols+c','c*cols+r','r*c','B','Each earlier row contributes cols elements, followed by offset c.','Derive flat indexes from layout and stride.'),
('ai','beginner','c-ai-03','Data input','Which function reads an entire line into a bounded character array?','gets','fgets','putchar','strlen','B','fgets accepts a destination size and can retain the newline when space permits.','Prefer bounded input and handle retained newlines explicitly.'),
('ai','beginner','c-ai-04','Initialization','What value do unspecified elements receive in double values[100]={0};?','Unspecified garbage','0.0','NaN','1.0','B','Aggregate initialization sets the first element to zero and zero-initializes the remainder.','Use aggregate zero initialization when every numeric entry should start at zero.'),
('ai','beginner','c-ai-05','Statistics','To compute a mean of n integer values safely, which accumulator is generally better?','char','A wider numeric type such as double','A one-bit field','FILE','B','A wider accumulator reduces integer overflow risk and preserves fractional results.','Choose accumulation types from worst-case total and desired precision.'),
('ai','beginner','c-ai-06','CSV processing','What character commonly separates fields in a simple CSV row?','Comma','Null pointer','EOF integer','Semicolon always','A','CSV commonly uses commas, though robust parsers must also handle quoting and embedded delimiters.','Define the input format instead of assuming every comma is a field boundary.'),
('ai','beginner','c-ai-07','Boolean masks','What does count += (x > threshold); do for integer count?','Adds x','Adds 1 when the condition is true, otherwise 0','Always adds 1','Cannot compile','B','Relational expressions produce 0 or 1, so the statement counts values above the threshold.','Use relational results carefully as integer indicators.'),
('ai','intermediate','c-ai-08','Floating point','Why is comparing computed doubles with == often risky?','double cannot store any number','Rounding can make mathematically equal results differ slightly','== compares addresses','Equality always raises an error','B','Many values and operations cannot be represented exactly in binary floating point.','Compare numeric results with a scale-appropriate tolerance when exact representation is not guaranteed.'),
('ai','intermediate','c-ai-09','Missing data','Which standard check detects a NaN floating-point value?','x==NAN','isnan(x)','x==0','sizeof(x)==0','B','NaN is unordered and must be detected with isnan from math.h.','Use floating-point classification functions for NaN and infinity.'),
('ai','intermediate','c-ai-10','Data normalization','What information is required for min-max scaling x to [0,1]?','Only x','The feature minimum and maximum','The number of source files','A pointer address','B','The scaled value is (x-min)/(max-min), with a policy required when max equals min.','Handle constant features explicitly when a scaling denominator can be zero.'),
('ai','intermediate','c-ai-11','Memory','How many double values are allocated by calloc(n,sizeof(double))?','One','n, initialized to all-bits-zero storage','sizeof(double)','An unknown count','B','calloc allocates n elements and initializes their bytes to zero.','Provide element count and element size separately to calloc.'),
('ai','intermediate','c-ai-12','Dataset traversal','What loop order usually improves locality for a row-major matrix?','Columns outer, rows inner','Rows outer, columns inner','Random indexes only','Order never matters','B','Visiting columns inside each row follows contiguous memory addresses.','Traverse data in the order it is laid out when performance matters.'),
('ai','intermediate','c-ai-13','Parsing','What should be checked after strtod parses a numeric field?','Only sizeof(double)','The end pointer and range error state','The pointer variable name','Whether stdout is open','B','The end pointer reveals unparsed input, and errno can report range failure.','Validated parsing must distinguish a number from partial or failed conversion.'),
('ai','intermediate','c-ai-14','Reproducibility','What does calling srand with the same seed normally provide for rand?','Cryptographic security','A repeatable pseudo-random sequence for that implementation','True physical randomness','Parallel execution','B','A deterministic PRNG repeats its sequence from the same seed within the same implementation.','Record seeds for reproducible experiments but do not treat rand as cryptographic.'),
('ai','advanced','c-ai-15','Numerical stability','Why can summing many small floats into a large float lose information?','Pointers become null','Limited precision may round away small increments','Loops stop early','Files close automatically','B','When magnitudes differ greatly, a small addend may fall below the representable spacing near the large sum.','Use suitable precision and stable accumulation methods for long numeric reductions.'),
('ai','advanced','c-ai-16','Data layout','What advantage can a structure-of-arrays layout offer for numeric processing?','It forbids loops','Contiguous values of one feature can improve vectorization and cache use','It removes all padding by rule','It makes every value a string','B','Feature-wise contiguous storage can suit SIMD and column-oriented operations.','Choose data layout from the dominant access pattern.'),
('ai','advanced','c-ai-17','Overflow safety','Before allocating rows*cols doubles, what must be validated?','Only that rows is positive','That both multiplications fit in size_t','That stdout is line-buffered','That doubles are integers','B','rows*cols and the later byte multiplication can overflow and create an undersized allocation.','Validate every dimension multiplication before allocating a tensor or matrix.'),
('ai','advanced','c-ai-18','Parallel data','What defect occurs when two threads increment one ordinary shared counter without synchronization?','Guaranteed perfect count','A data race','A syntax error','A file leak only','B','Concurrent unsynchronized read-modify-write operations can lose updates and create undefined behavior.','Protect shared mutable state or use appropriate atomic operations.'),
('ai','advanced','c-ai-19','Binary files','Why is directly writing a struct as a portable dataset format risky?','Structures cannot contain numbers','Padding, endianness and type representations can differ','fwrite always writes text','Files cannot store null bytes','B','Raw layout is implementation-dependent and may not be readable across builds or architectures.','Define a serialized format with explicit field sizes and byte order.'),
('ai','advanced','c-ai-20','Evaluation code','Why should train and test rows be separated before computing normalization statistics?','To reduce source code size','To prevent test information from leaking into training preprocessing','To make pointers global','To force integer division','B','Using test-set statistics influences the training pipeline and produces an optimistic evaluation.','Fit learned preprocessing only on training data, then apply it to held-out data.')
),
upserted as (
 insert into public.mcq_questions(slug,topic,subtopic,difficulty,target_path,time_limit_seconds,question_text,options,correction_rule,is_published,updated_at)
 select slug,'c',subtopic,difficulty,target_path,60,question,jsonb_build_object('A',a,'B',b,'C',c,'D',d),rule,true,now() from seed
 on conflict(slug) do update set subtopic=excluded.subtopic,difficulty=excluded.difficulty,target_path=excluded.target_path,question_text=excluded.question_text,options=excluded.options,correction_rule=excluded.correction_rule,is_published=true,updated_at=now()
 returning id,slug
)
insert into public.mcq_answer_keys(question_id,correct_option,explanation,option_explanations,updated_at)
select u.id,s.correct,s.explanation,
 jsonb_build_object(
  'A',case when s.correct='A' then 'Correct. '||s.explanation else 'Incorrect. '||s.rule end,
  'B',case when s.correct='B' then 'Correct. '||s.explanation else 'Incorrect. '||s.rule end,
  'C',case when s.correct='C' then 'Correct. '||s.explanation else 'Incorrect. '||s.rule end,
  'D',case when s.correct='D' then 'Correct. '||s.explanation else 'Incorrect. '||s.rule end
 ),now()
from upserted u join seed s using(slug)
on conflict(question_id) do update set correct_option=excluded.correct_option,explanation=excluded.explanation,option_explanations=excluded.option_explanations,updated_at=now();

commit;

select target_path,difficulty,count(*) from public.mcq_questions where topic='c' and slug like 'c-%' and is_published=true group by target_path,difficulty order by target_path,difficulty;
