
(() => {
  "use strict";
  const library = Array.isArray(window.CODEBHAVYA_PPT_LIBRARY) ? window.CODEBHAVYA_PPT_LIBRARY : [];
  const baseUrl = String(window.CODEBHAVYA_PPT_BASE || "").replace(/\/+$/, "");
  const $ = id => document.getElementById(id);
  const courseGrid=$("courseGrid"), pptSections=$("pptSections"), search=$("pptSearch"), showAllBtn=$("showAllBtn"), resultText=$("resultText"), emptyState=$("emptyState"), emptyReset=$("emptyReset"), navToggle=$("navToggle"), siteNav=$("siteNav"), toast=$("toast"), modal=$("pptModal");
  let activeCourse="all", toastTimer=0;
  const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");
  const objectUrl=(path)=>`${baseUrl}/${String(path).split("/").map(encodeURIComponent).join("/")}`;
  const pptUrl=(slug,file)=>objectUrl(`${slug}/${file}`);
  const previewUrl=(path)=>objectUrl(path);
  function showToast(msg){if(!toast)return;toast.textContent=msg;toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),1700)}
  function renderCourseCards(){courseGrid.innerHTML=library.map(c=>`<button class="course-card${activeCourse===c.slug?" active":""}" type="button" data-course="${esc(c.slug)}" aria-pressed="${activeCourse===c.slug}"><span class="course-symbol">${esc(c.short)}</span><h3>${esc(c.title)}</h3><p>${esc(c.description)}</p><span class="course-count">${c.topics.length} PPT${c.topics.length===1?"":"s"}</span></button>`).join("");courseGrid.querySelectorAll(".course-card").forEach(b=>b.addEventListener("click",()=>{activeCourse=b.dataset.course||"all";render();pptSections.querySelector(".course-section")?.scrollIntoView({behavior:"smooth",block:"start"})}))}
  function getFiltered(){const q=(search.value||"").trim().toLowerCase();return library.map(c=>{if(activeCourse!=="all"&&activeCourse!==c.slug)return {...c,topics:[]};return {...c,topics:c.topics.filter(t=>!q||[t.title,t.file,c.title,c.short].join(" ").toLowerCase().includes(q))}}).filter(c=>c.topics.length)}
  function card(c,t,i){const purl=previewUrl(t.preview), durl=pptUrl(c.slug,t.file);return `<article class="ppt-card"><div class="preview-media"><div class="preview-fallback">${esc(t.title)}</div><img loading="lazy" src="${purl}" alt="${esc(t.title)} PPT cover"><span class="preview-badge">PREMIUM PPT</span></div><div class="ppt-card-body"><h3>${esc(t.title)}</h3><div class="ppt-meta"><span class="badge premium">Premium</span><span class="badge">${esc(c.short)}</span><span class="badge">${Number(t.slides)||0} slides</span></div><div class="ppt-file">${esc(t.file)}</div><div class="card-actions"><button class="preview-btn" type="button" data-preview-course="${esc(c.slug)}" data-preview-file="${esc(t.file)}">Preview</button><a class="download-btn" href="${durl}" target="_blank" rel="noopener" data-ppt-title="${esc(t.title)}">↓ Download</a></div></div></article>`}
  function renderSections(filtered){pptSections.innerHTML=filtered.map(c=>`<section class="course-section" id="${esc(c.slug)}"><div class="course-section-head"><div><h2>${esc(c.title)}</h2><p>${esc(c.description)}</p></div><span class="section-count">${c.topics.length} presentation${c.topics.length===1?"":"s"}</span></div><div class="topic-list">${c.topics.map((t,i)=>card(c,t,i)).join("")}</div></section>`).join("");pptSections.querySelectorAll(".download-btn").forEach(a=>a.addEventListener("click",()=>showToast(`Opening ${a.dataset.pptTitle||"presentation"}…`)));pptSections.querySelectorAll(".preview-btn").forEach(b=>b.addEventListener("click",()=>openPreview(b.dataset.previewCourse,b.dataset.previewFile)));pptSections.querySelectorAll(".preview-media img").forEach(img=>img.addEventListener("error",()=>{img.style.display="none"}))}
  function openPreview(slug,file){const c=library.find(x=>x.slug===slug);const t=c?.topics.find(x=>x.file===file);if(!c||!t||!modal)return;$("modalImage").src=previewUrl(t.preview);$("modalImage").alt=`${t.title} PPT cover`;$("modalCourse").textContent=c.title.toUpperCase();$("modalTitle").textContent=t.title;$("modalSlides").textContent=`${t.slides} slides`;$("modalFilename").textContent=t.file;$("modalDownload").href=pptUrl(c.slug,t.file);modal.hidden=false;document.body.classList.add("modal-open");setTimeout(()=>modal.querySelector(".modal-close")?.focus(),0)}
  function closeModal(){if(!modal||modal.hidden)return;modal.hidden=true;document.body.classList.remove("modal-open")}
  function render(){renderCourseCards();const filtered=getFiltered();renderSections(filtered);const total=filtered.reduce((s,c)=>s+c.topics.length,0),q=(search.value||"").trim();if(activeCourse==="all"&&!q)resultText.textContent=`Showing all ${total} premium presentations across ${filtered.length} courses.`;else{const name=activeCourse==="all"?"all courses":(library.find(c=>c.slug===activeCourse)?.title||"selected course");resultText.textContent=`${total} presentation${total===1?"":"s"} found in ${name}${q?` for “${q}”`:""}.`}emptyState.hidden=total!==0;pptSections.hidden=total===0;showAllBtn.textContent=activeCourse==="all"?"All courses":"Show all courses"}
  search.addEventListener("input",render);showAllBtn.addEventListener("click",()=>{activeCourse="all";search.value="";render()});emptyReset.addEventListener("click",()=>{activeCourse="all";search.value="";render();search.focus()});if(navToggle&&siteNav)navToggle.addEventListener("click",()=>{const open=siteNav.classList.toggle("open");navToggle.setAttribute("aria-expanded",String(open))});modal?.querySelectorAll("[data-close-modal]").forEach(el=>el.addEventListener("click",closeModal));document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});const year=$("year");if(year)year.textContent=new Date().getFullYear();$("courseCount").textContent=String(library.length);$("pptCount").textContent=String(library.reduce((s,c)=>s+c.topics.length,0));$("slideCount").textContent=String(library.reduce((s,c)=>s+c.topics.reduce((x,t)=>x+(Number(t.slides)||0),0),0).toLocaleString());render();
})();
